version: '3.5'
services:
  dify2openai:
    container_name: dify2openai
    build:
      context: ..             # <-- Look up one directory (to the project root)
      dockerfile: config/Dockerfile # <-- Tell it where the Dockerfile is (relative to the new context)
    network_mode: bridge
    ports:
      - "3000:3000"
    restart: always
    environment: 
      - DIFY_API_URL=http://host.docker.internal:8080/v1
      - BOT_TYPE=Workflow
      - INPUT_VARIABLE=userInput
      - OUTPUT_VARIABLE=text